#!/usr/bin/env bash
#
#   /o o\    ^   ||''. ['|']
#  |o o <   //\  ||-+'   |
#   \o o/  //''\ ||  \  .|
#
# Description:              Smart theme generator
# Dependencies:             imagemagick, xorg
# Optionnal dependencies:   feh, grep, wget, notf, lamp
# Author:                   gawlk
# Contributors:             marinhoc

# ---
# TODO
# ---
#
# - Improve the selection of rgb in setters.rgb()
# - Improve the ifs in checkers.colors()
# - Find the perfect balance in tweakers.color()

# ---
# IMPORTS
# ---

. art-utils
art-utils.paths
art-utils.import

# ---
# SETUP
# ---

# Disable unicode.
LC_ALL=C
LANG=C

# Enable/Disable debug output (log.casual || log.dev)
log.casual

# Get all arguments
args=( $@ )

# Get the number of arguments
nb_args=$#

# If -q argument is found, disable logs
for(( ; i < $nb_args ; i++ )) { [[ "${args[$i]}" == "-q" || "${args[$i]}" == "-quiet" ]] && log.quiet; }

# ---
# MAIN
# ___

art.main() {
    initiators.init

    initiators.global_variables

    initiators.read_conf

    arguments.args

    # If new theme or -o paramater
    if [[ $create == true ]]
    then
        initiators.theme_folder

        generators.colors

        setters.theme

        tweakers.theme

        checkers.theme

        generators.theme_files
    else
        initiators.read_colors
    fi

    generators.conf_file

    generators.xresources_file

    updaters.desktop

    log.is_loud && pale -n 1

    pure.check_program_in_path "notf" && notf "Theme: $theme"

    pure.check_program_in_path "lamp" && lamp
}

# ---
# LAUNCH
# ---

art.main
