#!/usr/bin/env bash

check_diff() {
    diff=$(( $1 - $2 ))
    # Get absolute value
    diff=${diff#-}
    echo $diff
}

# Check if two colors are similar
check_if_similar() {
    hex_to_rgb $1
    R1=$R
    G1=$G
    B1=$B

    hex_to_rgb $2
    R2=$R
    G2=$G
    B2=$B

    diffR=$(check_diff $R1 $R2)
    diffG=$(check_diff $G1 $G2)
    diffB=$(check_diff $B1 $B2)

    diff=$(( $diffR + $diffG + $diffB ))

    [ $diff -lt $min_diff_rgb ] && echo "true" || echo "false"
}

# Check the similarity between red, green and blue
check_themes() {
    array=("${@}")
    blk=${array[0]}
    gry=${array[1]}
    
    adjust_colors "gry"

    red=${array[2]}
    grn=${array[3]}
    blu=${array[4]}
    wht=${array[5]}

    while [[ $(check_if_similar $red $grn) == "true" && $(check_if_similar $red $blu) == "true" ]]; do adjust_colors "red" "grn" "blu"; done
    while [[ $(check_if_similar $red $grn) == "true" ]]; do adjust_colors "red" "grn"; done
    while [[ $(check_if_similar $red $blu) == "true" ]]; do adjust_colors "red" "blu"; done
    while [[ $(check_if_similar $grn $blu) == "true" ]]; do adjust_colors "grn" "blu"; done

    array=( "$blk" "$gry" "$red" "$grn" "$blu" "$wht" )
}

check_colors() {
    print "Checking colors..."

    check_themes "${dark[@]}"
    dark=("${array[@]}")
    check_themes "${light[@]}"
    light=("${array[@]}")
}
