#!/usr/bin/env bash

echo "Updating xrdb..."
xrdb ${HOME}/.Xresources

echo "Updating 2bwm..."
xdotool key "ctrl+super+r"

echo "Updating polybar..."
polybar-msg cmd restart &> /dev/null

echo "Updating dunst..."
killall dunst &> /dev/null
dunst \
    -lb "$blk" \
    -nb "$blk" \
    -cb "$blk" \
    -lf "$wht" \
    -bf "$wht" \
    -cf "$wht" \
    -nf "$wht" &
