#!/usr/bin/env bash

print_help() {
    print '\nusage: art [-h] [-a] [-c] [-d | -l | -s] [-i "file" "name" | -n "name" | -r | -u ["name"]] [-o] [-q]'
    
    print '\nart - Theme generator'

    print '\nArguments:'
    print '(none)               Load the current theme'
    print '-h                   Show this help message and exit'
    print '-a                   Show a list of all available themes'
    print '-c                   Print the current theme'
    print '-d                   Load the dark version of the theme'
    print '-l                   Load the light version of the theme'
    print '-s                   Load the opposite version of the theme'
    print '-i "file" "name"     Create theme using an image'
    print '-n "name"            Load a specific theme'
    print '-r                   Load a random theme'
    print '-u [ "name" ]        Create a theme using a random image from unsplash,' 
    print '                     the optional argument is a keyword to load specific images'
    print '-o                   Override an existing theme (used with -i'
    print '-q                   Quiet mode'
    print ''
}
