#!/usr/bin/env bash

init() {
    # Set PATH variables
    bin="${HOME}/.bin"
    colr="${HOME}/.colors"
    dir="${HOME}/.themes"
    lock="${bin}/lock.png"
    # Number of colors to generate from picture
    nb=10

    min_diff_rgb=40
    # Used in the tweak_gry function
    diff_gry_blk=30
    # Used in the out_of_bound function
    out_of_bound1=10
    out_of_bound2=245
    # arrays
    names=( "blk" "gry" "red" "grn" "blu" "wht" )
}

init_folder() {
    echo "Creating the theme..."
        
    mkdir -p ${dir}/${theme}
    cp $path ${dir}/${theme}/wal.${ext} &> /dev/null
}
