#!/usr/bin/env bash

# Set the red-est, green-est and blue-est colors
set_rgb() {
    oldRpctg=-1000
    oldGpctg=-1000
    oldBpctg=-1000

    for (( i=$1; i<=$2; i++ ))
    do
        hex_to_rgb "${colors[$i]}"

        Rpctg=$(( ( R - G ) + ( R - B ) ))
        Gpctg=$(( ( G - R ) + ( G - B ) ))
        Bpctg=$(( ( B - G ) + ( B - R ) ))

        [[ $Rpctg -gt $oldRpctg ]] && oldRpctg=$Rpctg && red=${colors[$i]}
        [[ $Gpctg -gt $oldGpctg ]] && oldGpctg=$Gpctg && grn=${colors[$i]}
        [[ $Bpctg -gt $oldBpctg ]] && oldBpctg=$Bpctg && blu=${colors[$i]}
    done
}

# Set colors of a theme
set_themes() {
    if [[ $1 == "dark" ]]
    then
        blk=${colors[0]}
        wht=${colors[$(( nb - 1 ))]}
        bound1=$(( ( nb / 2 ) - 1 ))
        bound2=$(( nb - 2 ))
    else
        blk=${colors[$(( nb - 1 ))]}
        wht=${colors[0]}
        bound1=0
        bound2=$(( nb / 2 ))
    fi

    array[0]=$blk
    array[1]="#"
    set_rgb $bound1 $bound2
    array[2]=$red
    array[3]=$grn
    array[4]=$blu
    array[5]=$wht
}

set_colors() {
    print "Setting colors..."
    
    set_themes "dark"
    dark=("${array[@]}")
    set_themes "light"
    light=("${array[@]}")
}
