#!/usr/bin/env bash
#
# Description: Update config's colors
# Dependencies: art, notf

# Huge thanks to Dylan Araps for this
set_special() {
    sequences+="\033]${1};${2}\007"
}

# Huge thanks to Dylan Araps for this
set_color() {
    sequences+="\033]4;${1};${2}\007"
}

# Huge thanks to Dylan Araps for this
update_terms() {
    # spe
    set_special 10  "$wht"
    set_special 11  "$blk"
    set_special 12  "$wht"
    set_special 13  "$wht"
    set_special 14  "$blk"
    set_special 708 "$blk"

    # blk
    set_color 0  "$blk"
    
    # gry
    set_color 8  "$gry"
    
    # red
    set_color 1  "$red"
    set_color 5  "$red"
    set_color 9  "$red"
    set_color 13 "$red"
    
    # grn
    set_color 2  "$grn"
    set_color 3  "$grn"
    set_color 10 "$grn"
    set_color 11 "$grn"
    
    # blu
    set_color 4  "$blu"
    set_color 6  "$blu"
    set_color 12 "$blu"
    set_color 14 "$blu"

    # wht
    set_color 7  "$wht"
    set_color 15 "$wht"

    # else
    sequences+="\033]4;66;${blk}\007"
           
    for term in /dev/pts/[0-9]*
    do  
        [[ -w "$term" ]] && printf "%b" "$sequences" > "$term" &
    done
}

update() {
    print "Updating the wallpaper..."
    wal=`ls ${dir}/${theme} | grep "wal"`
    [ -n "$wal" ] && feh --bg-fill ${dir}/${theme}/${wal}

    . EDITME

    print "Updating open terminals..."
    update_terms
}
