#!/usr/bin/env bash
#
# Description:              Art api
# Dependencies:             art
# Optionnal dependencies:   none
# Author:                   gawlk
# Contributors:             none

# ---
# IMPORTS
# ---

. art-utils

# ---
# GLOBAL
# ---

art-api.get_brightness() {
    local brightness=$( initiators.read_line "$conf_file" "brightness" )
    checkers.is_brightness "$brightness" && printf '%s\n' "$brightness" || printf '%s\n' ""
}

art-api.get_colors() {
    log.quiet
    log.casual
    initiators.read_colors
    log.loud
    printf '%s\n' "${final_colors[@]}"
}

art-api.get_theme() {
    local theme=$( initiators.read_line "$conf_file" "theme" )
    checkers.is_theme "$theme" && printf '%s\n' "$theme" || printf '%s\n' ""
}
