#!/usr/bin/env bash
#
# Description:              Art utilities
# Dependencies:             art
# Optionnal dependencies:   none
# Author:                   gawlk
# Contributors:             none

# ---
# LOCAL
# ---

# Import functions and libraries
art-utils.import() {
    # Functions
    . ${fun_dir}/arguments
    . ${fun_dir}/checkers
    . ${fun_dir}/converters
    . ${fun_dir}/generators
    . ${fun_dir}/helpers
    . ${fun_dir}/initiators
    . ${fun_dir}/setters
    . ${fun_dir}/tweakers
    . ${fun_dir}/updaters

    # Libraries
    . log || ( printf "ERROR: Couldn't import the log library" && exit 1 )
    . pure  || ( printf "ERROR: Couldn't import the pure library" && exit 1 )
}

# Set various paths
art-utils.paths() {
    # Directories
    cnf_dir="${HOME}/.config/art"
    fun_dir="/usr/local/bin/art_functions"
    thm_dir="${cnf_dir}/themes"

    # Files
    conf_file="${cnf_dir}/art.conf"
    edme_file="${cnf_dir}/EDITME"
    xres_file="${HOME}/.Xresources.colors"
}

# ---
# MAIN
# ---

art-utils.main() {
    art-utils.paths

    art-utils.import
}

# ---
# LAUNCH
# ---

art-utils.main